version: 2.1
jobs:
  build:
    docker:
      - image: unpause/swiftvideo:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Public interface tests
          command: |
            swift test -c release --filter swiftVideoTests
      #disable for now since clang crashes when running this command for some reason.
      - run:
          name: Internal tests
          command: |
            rm -rf .build
            swift test --filter swiftVideoInternalTests
