name: Swift

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: unpause/swiftvideo:latest

    steps:
    - uses: actions/checkout@v1
    - name: Run public tests
      run: swift test -Xswiftc -DUSE_FFMPEG -Xswiftc -DUSE_FREETYPE -c release --filter swiftVideoTests
    - name: Run internal tests
      run: swift test -Xswiftc -DUSE_FFMPEG -Xswiftc -DUSE_FREETYPE --filter swiftVideoInternalTests
